### ISSUE TITLE
macOS Crash on Deleting Instrument

### ISSUE THREAD

**Issue by Ravancloak** [BambooTracker/BambooTracker#275]
## Bug Description

Pressing delete key twice while an instrument is open and edit mode is on is consistently crashing bambootracker.

## How to reproduce

I cannot reproduce in a new module or the one module I checked. Easily reproducible in the attached module.

~~1. Enable edit mode~~ (this doesn't matter)
2. Edit instrument (I always double click it to open the window)
3. Press the delete key twice

## System Information

- macOS 10.13.6
- BambooTracker v0.4.4 release
- Official

[Module_and_CrashReport.zip](https://github.com/rerrahkr/BambooTracker/files/5435969/Module_and_CrashReport.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. But I could not replicate this bug in macOS mojave 10.14.6. Are you focusing on the instrument editor when this bug occurs, or instrument list?

**Comment by Ravancloak** [comment]
here is a screen recording of the crash (sorry it took me so long to send this)

https://user-images.githubusercontent.com/54685652/104357981-dd29b080-54db-11eb-9228-123900b7b043.mp4

**Comment by rerrahkr** [comment]
Tried again, but I could not reproduce. I suppose this is probably a hardware performance related issue.
Due to the nature of the event, if you call an event to delete the same instrument during the deletion process, it may cause a memory error. Please avoid making the same call in a short period of time as much as possible.
