### ISSUE TITLE
SCCI licensing

### ISSUE THREAD

**Issue by fpesari** [BambooTracker/BambooTracker#357]
Hello,

I looked at the SCCI license but it was in Japanese, so I gave it to DeepL for a rough translation. Here is the result:

```
About scci.dll license

This software is freeware.
There are no restrictions on the use or redistribution of this DLL or the accompanying source code for development
There are no restrictions on the use and redistribution of this DLL and the accompanying development source code, including commercial use.
You are free to use this software at your own risk.

The user is responsible for any damage to data or equipment caused by using this DLL.
The user is responsible for any damage to data or equipment caused by using this DLL.

The source code of the DLL itself is for the purpose of interface integration.
As for the source code of the DLL itself, since the purpose is to integrate the interface
The source code of the DLL itself is for the purpose of interface integration, so we will consider providing it if you contact us with your feedback.

That's all.
```

It seems that this license could be considered a custom permissive license however the legal language does not seem clear enough. In any case, it's not FSF or OSI approved and this means some distros cannot distribute it.

I actually made an openSUSE package for bambootracker. openSUSE has a [policy](https://en.opensuse.org/openSUSE:Packaging_guidelines#Licensing) which allows only FLOSS software in the community repos. If SCCI is nonfree software, that means I can only make a package for bambootracker:
1. If SCCI (including its source code) is relicensed to a license accepted by the OSI
2. If I can build BambooTracker without SCCI

I would really like to distribute BambooTracker from the music repository I help run, GeekosDAW, as I consider it a must-have for chiptune artists. 

Is there any way to solve this issue by contacting the author for relicensing or by enabling working SCCI-less builds?

**Comment by OPNA2608** [comment]
> I looked at the SCCI license but it was in Japanese, so I gave it to DeepL for a rough translation. Here is the result:

Machine translators have a hard time dealing with manually-inserted newlines like in that file. After clearing those up pre-translation:

> What is the license for scci.dll
> 
> This software is freeware. There are no restrictions on the use or redistribution of this DLL or the accompanying development source code, including commercial use. You are free to use it at your own risk.
> 
> The user is responsible for any damage to data or equipment caused by the use of this DLL.
> 
> The source code for the DLL itself is intended to integrate the interface, so we will consider providing it to you if you contact us with your feedback.
> 
> That's all.

From my understanding [the SCCI DLL in question is not being distributed with this project and needs to be manually downloaded and installed](https://github.com/rerrahkr/BambooTracker/wiki/Configuration#real-chip-interface), only a set of headers (`/BambooTracker/chip/scci/`) with defines, enums and method declarations that allow it to be dynamically loaded if desired is used. I doubt that makes enough of a difference in legalese though.

Either way, +1 on the request to contact the author for a clarification on the headers' license @rerrahkr. [Here's a list of licenses](https://opensource.org/licenses/alphabetical) (unfortunately for the author, in English), I think the [zlib license](https://opensource.org/licenses/Zlib) is fairly simple, GPL-compatible and similar to the original one (including the version on the website). And if there's no response or a "no" on the license change suggestion, then making it optional would be nice.

> I actually made an openSUSE package for bambootracker.

If you do end up pushing that to your distro's package collection, feel free to add your zypper/dnf/etc [package installation commands](https://github.com/rerrahkr/BambooTracker#packages-macos-linux-bsd) for regular end-users and [dependency install instructions](https://github.com/rerrahkr/BambooTracker#dependencies) for manual compilation to the README. If it falls through due to the license thing, there's always our pre-compiled version. :pensive:

**Comment by rerrahkr** [comment]
He describes the license in a little more detail in `ライセンス及び、今後の対応ハードウェアについて` on [his site](http://www.pyonpyon.jp/~gasshi/fm/old/scci.html).

translated by DeepL:
> SCCI is a freeware.
> There are no restrictions on the use or redistribution of this DLL and the sample code for development.
> You can use it freely at your own risk.
> If you attach the dll to your application, there is no need to indicate the license.
> However, this does not mean that the copyright is waived.
> In addition, the use of this DLL with a wrapper to support hardware that does not support SCCI is basically prohibited because it is not for development purposes.
>
> For future SCCI support, we would like to actively support hardware that is considered to be compatible and for which we can provide information and support.
> It is assumed that the supported hardware will be distributed and can be used by many people.

I will propose to the author on Twitter to change the license for the header or to make it dual license.

**Comment by rerrahkr** [comment]
I would like to confirm that openSUSE does not allow custom licenses, and that they must be OSI-approved licenses?

**Comment by freq-mod** [comment]
https://en.opensuse.org/openSUSE:Packaging_guidelines#Licensing

>Software licenses should comply with the Open Source Definition (which is currently at version 1.9).

**Comment by rerrahkr** [comment]
In other words, even if it is a custom license, as long as it is in accordance with the Open Source Definition, it is fine.

The description of the header files in the current license is:

1. There are no restrictions on use or redistribution.
2. The author assumes no responsibility for any damage caused by use.

I think it is closer to [MIT No Attribution (MIT-0)](https://opensource.org/licenses/MIT-0), but:

> If you attach the dll to your application, there is no need to indicate the license.
> However, this does not mean that the copyright is waived.

It is unclear whether this line refers to the obligation to include the copyright and license notices.
By checking these two points, we can tell if it is Open source. However, in order to clarify the interpretation of the license, we want to have it changed to an OSI-approved license if possible. Is my understanding correct?

**Comment by freq-mod** [comment]
I think yes, but contacting the author and asking about clarifying that one aspect of his licence won't hurt

**Comment by fpesari** [comment]
> By checking these two points, we can tell if it is Open source. However, in order to clarify the interpretation of the license, we want to have it changed to an OSI-approved license if possible. Is my understanding correct?

Relicensing to a similar but standardized license would leave no doubt whatsoever for packagers, that's for sure!

I don't know if you already contacted the author. I would not recommend the MIT-0 because it's not actually OSI or FSF approved. I would personally recommend the ISC license because it is very simple, allows everything the current license does and is approved by both the OSI and the FSF:

```
ISC License

Copyright (c) [year], [fullname]

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

**Comment by OPNA2608** [comment]
> In any case, it's not FSF or OSI approved
> If SCCI (including its source code) is relicensed to a license accepted by the OSI
> I would not recommend the MIT-0 because it's not actually OSI or FSF approved.
> …and is approved by both the OSI and the FSF

Sort of off-topic but you're mentioning OSI and FSF together alot. For my own understanding in the future: Whose approval matters for openSUSE, OSI or FSF? Or both? Or is it good enough for openSUSE if you can argue that a license complies with the OSD, with explicit OSI / FSF approval being a "nice-to-have"?

I'm asking because the OSI and FSF don't always have the same opinion on a license, see the Sybase Open Watcom Public License for an example of this: [accepted by OSI](https://opensource.org/licenses/sybase.php), [rejected by FSF](https://www.gnu.org/licenses/license-list.html#Watcom) and [multiple](https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses) [distributions](https://lists.debian.org/debian-legal/2006/07/msg00014.html).

---

That aside, MIT-0 *does* seem to be OSI-approved.

[It's on their list of approved licenses.](https://opensource.org/licenses/alphabetical)

> The following licenses have been approved by the OSI. The parenthesized expression following a license name is its SPDX short identifier (if one exists).

> - MIT No Attribution License (MIT-0)

[And their page for it includes a big "approved" image.](https://opensource.org/licenses/MIT-0)

![grafik](https://user-images.githubusercontent.com/23431373/116048175-2fe73c80-a675-11eb-88bc-9b71d7d35855.png)

**Comment by fpesari** [comment]
> That aside, MIT-0 _does_ seem to be OSI-approved.

Whoops, sorry on that! It kinda makes sense that the MIT-0 is OSI-approved, since it is less restrictive than the ordinary MIT.

> Sort of off-topic but you're mentioning OSI and FSF together alot. For my own understanding in the future: Whose approval matters for openSUSE, OSI or FSF? Or both? Or is it good enough for openSUSE if you can argue that a license complies with the OSD, with explicit OSI / FSF approval being a "nice-to-have"?

From my own experience, this is rarely an issue since most packages nowadays adopt only a subset of existing licenses (MIT, BSD 0/2/3 clause, GPLv2-3, AGPLv3, LGPL2.1, Apache 2.0, MPL, EPL, ISC, zlib, Boost and very rarely Artistic License 2.0 and CPAL). In the case of permissive licenses, licenses are IMHO often a cultural choice (e.g. language X uses licenses Y, libraries also use Y), as the differences are minimal (my personal favorite is the Apache 2.0 license). Copyleft is the only case in which the license can radically affect development (for example, AGPLv3 prevents people from taking a program and turning it into SaaS without giving back their own modifications).

Some distros follow the OSI, some the FSF, some their own rules (e.g. Debian with their DFSG). I would personally go with the FSF, because the OSI in at least one case has not accepted a valid license, the WTFPL, seemingly because it has a bad word in its name (I actually agree it's not a good license and the CC0 should be used instead, but that's beside the point). Between the two, the FSF is also the one more concerned about user freedom than coporations, a view reflected in their support of copyleft and sponsorships :rofl: ([FSF](https://www.fsf.org/patrons/) vs [OSI](https://opensource.org/sponsors)). That said, there are good people concerned with user freedom in the OSI too, and there is much overlap in the statement on the OSI homepage (which speaks clearly of "software freedom") and FSF's mission.

Finally, openSUSE is not so strict on licenses for unofficial packages, but when a package reaches the official repositories then there could be some discussions. Maybe SCCI could be judged OK on openSUSE but not on stricter distros like Debian. In any case, the fact that the license is in Japanese and has not been reviewed by lawyers or tested in courts certainly brings some uncertainty. The only ones who can really claim something to be OSD-compliant is the OSI itself, so in my view there is no escape from using one of their approved licenses.

**Comment by rerrahkr** [comment]
I sent the message to the author a month ago, but they has never replied.
https://twitter.com/RerrahKRynn/status/1389420553807618055
So is it better to make SCCI removable from the compilation source?

**Comment by OPNA2608** [comment]
I think that would be for the better.
(C86CTL could also be made optional, I think neither of those real chip APIs actually compile & work on non-Windows?)

**Comment by rerrahkr** [comment]
Since both SCCI and C86CTL use dlls, I don't think the real chip interface is useful outside of Windows.
Would it be better to add an option to enable them only when compiling on Windows?

**Comment by OPNA2608** [comment]
Making a combined option that enables/disables both of them seems fine to me. I have no string preference for whether it should or shouldn't be enabled by-default on Windows, we can just explicitly enable it on all of our CI builds.

**Comment by rerrahkr** [comment]
@fpesari The build instruction has been modified to exclude SCCI and C86CTL in the compilation by default on Linux.

**Comment by fpesari** [comment]
Thank you! I see no problems now, I think you can close this issue :smiley:
