### ISSUE TITLE
Linux - High latency when using Pulse backend

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#363]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When I set BambooTracker to output through PulseAudio, the audio latency is very high and does not decrease as I decrease "Buffer length".

## How to reproduce

1. Install BambooTracker on Linux (eg. Arch).
2. Open the Config dialog.
3. In the Sound tab, switch the API to Pulse, and optionally decrease "Buffer length".

## Solution

For some reason, PulseAudio and/or RtAudio uses a very high latency by default. Even if you feed it short buffers each time, it'll request many buffers from your app and queue them up for a long time (I'd estimate as over 100ms) before playing them. In recent RtAudio versions (after [my patch was merged](https://github.com/thestk/rtaudio/pull/263)) this can be fixed by assigning numberOfBuffers manually:

```diff
diff --git a/BambooTracker/audio/audio_stream_rtaudio.cpp b/BambooTracker/audio/audio_stream_rtaudio.cpp
index f2fcfcf..f685f34 100644
--- a/BambooTracker/audio/audio_stream_rtaudio.cpp
+++ b/BambooTracker/audio/audio_stream_rtaudio.cpp
@@ -61,6 +61,7 @@ bool AudioStreamRtAudio::initialize(uint32_t rate, uint32_t duration, uint32_t i
 	RtAudio::StreamOptions opts;
 	opts.flags = RTAUDIO_SCHEDULE_REALTIME;
 	opts.streamName = AUDIO_OUT_CLIENT_NAME;
+	opts.numberOfBuffers = 2;
 
 	auto callback =
 			+[](void* outputBuffer, void*, unsigned int nFrames,
```

I'm not sure if hard-coding 2 blocks of "Buffer length" ms each, without a configuration option to pick more or less, is good enough. I'm not sure how it affects non-Pulse audio backends. I suspect 2 blocks is a reasonable default, since it's what qjackctl defaults to in JackAudio.

What was your intent behind the "Buffer length" slider? (With my proposed patch, the Pulse audio latency is up to twice the buffer length slider, and I haven't tested ALSA or Windows/Mac.)

(On an unrelated note, my hardware ALSA device often disappears from BambooTracker's ALSA device list. On yet another unrelated note, I think BambooTracker should allow connecting to all `pcm` ALSA devices including pulse and pipewire, not just `hw` ones. Explanation at https://www.volkerschatz.com/noise/alsa.html.)

## System Information

- **Operating System**: Arch Linux, latest
- **BambooTracker Version**: unstable-89d99b3d0b459d17b9cb0d07052c8d99724046c3
- **Build Type**: Arch Linux bambootracker-git PKGBUILD

**Comment by OPNA2608** [comment]
To recap what we were discussing on Discord, regarding the unrelated notes:

1. RtAudio can not get device information about ALSA devices that are in use at the time of the combobox' content generation. Since we use that to filter the list of returned devices for anything that has 2 or more output channels, such devices disappear from the list. (ALSA devices may also disappear from the list if PulseAudio is currently playing something, and reappear when PulseAudio "frees" it after no audio has been playing on it for a while.)
I only skimmed it but [RtApiAlsa::getDeviceInfo](https://github.com/thestk/rtaudio/blob/c9bf99d414cf81d19ef0ddd00212a4a58ccd99c6/RtAudio.cpp#L7228-L7516) appear to try to open a connection to the selected device to query its details, which will fail if the device is already in use (e.g. `RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.`).

2. RtAudio only seems to look up `hw` ALSA devices. I built a fairly small test application that queries all ALSA devices & their details via RtAudio and all I got were `hw:` devices, so this is not our filtering's fault. You should check [RtApiAlsa::getDeviceCount](https://github.com/thestk/rtaudio/blob/c9bf99d414cf81d19ef0ddd00212a4a58ccd99c6/RtAudio.cpp#L7179-L7226) and experiment with a test application of your own to confirm this observation.

Both of those issues lie within RtAudio AFAICT, but the way `getDeviceInfo` is implemented may be an ALSA API limitation? I haven't checked though…

**Comment by rerrahkr** [comment]
Thanks for your report. Unfortunately, I'm not a Linux user, and I'm not familiar with how they work, so I can't confirm how PulseAudio and ALSA behave, or how they change with this fix. Anyway I'll try to create a PR for now.

The buffer length was supposed to be the sample length that audio needs for a single call, but we made various changes so it may actually be different.
