### ISSUE TITLE
[Feature] - When exporting VGM, save mixing levels in extra header?

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#436]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Currently when enabling mixing levels in BambooTracker (eg. making the SSG quieter than default), .vgm file exports don't contain mixing levels, leading to the SSG being louder in .vgm export than in the tracker.

The mixing levels could be saved in the .vgm file's extra header. VGM 1.70 (2014) added support for an extra header ([wiki](https://vgmrips.net/wiki/VGM_Specification#Extra_Header)), which can contain chip volume offsets. But BambooTracker currently doesn't write the [pointer to the extra header](https://vgmrips.net/wiki/VGM_Specification#:~:text=%20vgm%201.70%20additions%3A%20).

Is the extra header supported in players? ValleyBell [says](https://discord.com/channels/218044739893592064/755901971633799228/915385477266296862) libvgm supports the extra header, because "pretty much all PC-98 rips use it".

> https://vgmrips.net/forum/viewtopic.php?t=3747 example pack with SSG adjust

I don't think copying the offset directly from BambooTracker's internal mixer is good enough, since in_vgm 0.50.1's SSG is 5-6 dB louder than BambooTracker's SSG with no mixer active (using FM as a baseline, see below). You'll have to multiply the SSG volume by 0.3 or so, while converting module-specific mix levels to .vgm format.

@ValleyBell describes .vgm mixing as follows:

> The "absolute value 100%" = the default volume of the libvgm core (which can be really arbitrary)
> The "relative value 100%" = the default volume of the chip in VGMs (different from the default sound core volume)
> VGMs come with a pre-set balance for certain chips. e.g. YM2612's default VGM volume is 100%, SN76489's default volume is 50%, so that MegaDrive VGMs sound good
> In case of the YM2203/2608/2610 SSG, it is highly recommended to use a relative volume, as it changes the SSG volume based on the volume of the FM part.

is 100% relative volume equivalent to no extra header?

> yes

So in that case, it should be sufficient to output BambooTracker's FM and SSG volume levels, but multiply the SSG volume level by 0.3 or so.

## How much quieter should SSG be? (I don't know.)

Sample module: [bambootracker vgm mixing.zip](https://github.com/BambooTracker/BambooTracker/files/7629620/bambootracker.vgm.mixing.zip). I recorded this module from BambooTracker and in_vgm, applied two passes of Audacity's lowpass filter at 500 Hz and 48 dB slope, then one pass of Audacity's highpass filter at 16 Hz and 6 dB slope, then used the Contrast tool to measure how much louder the FM was than the SSG in each file.

On Windows, BambooTracker FM was 9.7 dB louder than SSG, and Winamp in_vgm (libvgm) FM was 4.64 dB louder than SSG, making Winamp's SSG 5.06 dB louder than BambooTracker's.

On Linux, BambooTracker FM is 9.44 dB louder than SSG, and qvgmsplit (libvgm) FM was 3.93 dB louder than SSG, making WinAmp's SSG 5.51 dB louder than BambooTracker's. I'm not sure why the discrepancy exists.

**Comment by rerrahkr** [comment]
Thank you for your request. I know there is a volume header for vgm, but I don't support it at this time because the difference between "the default volume of the chip in VGM" and BT's two OPNA emulations is not clear.

To begin with, please note that I cannot guarantee the correctness of the mixing level presets provided in the module properties.
Since OPNA has different mixing levels for FM and SSG on different soundboards, so I need to investigate the volume difference from all target boards. However, since I do not have them and estimated the volume difference from the output of hoot (#72), I do not know if the mixing presets are "correct". Until this issue is resolved, I think I should avoid exporting mixing level settings.

**Comment by rerrahkr** [comment]
It's been a while, but I will try to export the current mixing settings to VGM.
Should I just export the SSG volume difference relative to libvgm?

**Comment by ValleyBell** [comment]
For the OPN/OPNA SSG volume, I recommend going with the "relative volume". (i.e. `(volume_float * 0x100) | 0x8000`)

**Comment by rerrahkr** [comment]
I found an offset of -5.2 dB in the volume ratio between single FM and single SSG. But when multiple FMs and SSGs are played simultaneously, is the volume normalized? It cannot keep the mix setting properly. In some cases, the user may need to manually adjust the volume offset.

**Comment by ValleyBell** [comment]
Yes, VGMPlay reduces the volume by 50% for "dual-instance" chips. (The factor is applied to the *default* volume for a chip, but not to user-defined absolute values.)
Thus, when you have 2xYM2612 + 1xAY8910, then the FM chip is only *half as loud* compared to 1xYM2612 + 1xAY8910.

This is for separate YM2612 and AY8910 chips.

---

If you look at the YM2608's FM and SSG parts, then both parts are scaled by the same factor by default.
Using the *relative* volume setting keeps the volume balance intact between FM and SSG parts even if there is any scaling due to multiple instances of a chip.
However using if you override the volume using the *absolute* setting, results will differ depending on the number of instances of the YM2608.

---

Sorry for all the mess. The volume mixing formula unfortunately dates back to 2010 when I was trying to figure out how to get reasonable default volume values.

**Comment by rerrahkr** [comment]
Thanks for the info. I will try to allow the user to set the volume offset.

**Comment by rerrahkr** [comment]
Implemented in #472.
