### ISSUE TITLE
[Feature] - Bold fonts

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [BambooTracker/BambooTracker#461]
There is no checkbox for bold mode for selected font
current pattern editor is illegible and not enough contrast on all default color themes
Especially in dynamic
![2022-08-25_195225](https://user-images.githubusercontent.com/88002487/186725663-4af5a581-7b26-4251-b88d-cdae5cdad50b.png)

**Comment by rerrahkr** [comment]
The visibility problem should be solved. I'll see if I can add a font weight setting.

**Comment by NEO-SPECTRUMAN** [comment]
is it posible to add smooth vertical scrolling?
with moar contrast theme
maybe it will decrease visibility problem
![2022-08-26_204820](https://user-images.githubusercontent.com/88002487/186963238-a348d2b6-09c5-43ab-b7e8-72f23232445f.png)

**Comment by rerrahkr** [comment]
> is it posible to add smooth vertical scrolling?

You mean the coarse scrolling during playback? It is caused by a poor implementation of the playback routine and cannot be easily dealt with.

> with moar contrast theme

I am not a good designer, so I don't know if I can make a desirable theme. Personally, I think "FT-ish" is better in terms of contrast, but it would be best to change the colors in the appearance settings by referring to the color schemes of other applications by hand.

**Comment by rerrahkr** [comment]
Font settings is changed from 482441ffea8ad94d7dbabef81610624398f47931. You can change font family, size and weight in the font settings dialog.
Note: previous font settings are not inherited, so you must be manually set to the appropriate ones.

**Comment by NEO-SPECTRUMAN** [comment]
> You mean the coarse scrolling during playback?

yes

but I'm not 100% sure that it will help
